### PR TITLE
WIP: ISS Fixes 

### PR DESCRIPTION
**Pull request by ssmusoke**
#8 - Add STI symptoms to ART encounter page 

#22 Add co-morbidities to the ART Summary page (relevant medical conditions) 

Upgrade to the latest version of UgandaEMR

Feedback from January 2019 Testing 
- https://trello.com/c/zQF0fYaM
- https://trello.com/c/z7zARNux
- https://trello.com/c/bFa1K6qU
- https://trello.com/c/7YOpyWoV
- https://trello.com/c/uA7rfOq5

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama Needs to have this PR merged first which fixes snapshot builds https://github.com/METS-Programme/openmrs-module-aijar/pull/362

**Comment by ssmusoke** [comment]
@slubwama FYA

**Comment by ssmusoke** [comment]
@slubwama Any feedback

**Comment by ssmusoke** [comment]
@slubwama FYA

**Comment by ssmusoke** [comment]
@slubwama FYA - 2 weeks later

**Comment by slubwama** [comment]
@sqaush your commits tooo many commits

**Comment by slubwama** [comment]
@ssmusoke provide comprehensive details of "Feedback from January 2019 Testing"

**Pull request merged**
