### PR TITLE
Initial Commit 

### PR DESCRIPTION
**Pull request by ssmusoke**
The trello card with the information is https://trello.com/c/5GPomqSH

1. New custom module code 
2. Migration script for concepts so as not to conflict with UgandaEMR 
3. Update of 122a-HIV_Care-ARTCard-SummaryPage.xml and 122a-HIV_Care-ARTCard-EncounterPage.xml to use the new concepts 
4. Fixes to the following issues:
   * 1 - ART Encounter disable "Other ARV"
   * 2 - Include variable to capture ART pill balances 
   * 3 - Add field to capture other reasons for POV not eligible
   * 9 - Enable saving for visit types 
   * 23 - Return ART summary form sections 

To deploy the changes:

1. Create a new database
2. Import the sample data file 
3. Run the upgrade_to_2x script in api/resources/sql
4. Start the SDK server pointing to the database 

@slubwama Testing instructions

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama I have updated the sql script to correct a malformed concept what was breaking the UgandaEMR liquibase changesets

**Comment by slubwama** [comment]
@ssmusoke 
1. there is a build error https://pastebin.com/hx3An3VU
2. Squash your commits

**Comment by ssmusoke** [comment]
@slubwama You need to ensure that you have the latest aijar version, you should use `mvn clean install -U` as there was a change in this initializer 

You can squash these commits as part of the Merge Pull Request feature, it was taking alot of time being a new repo

**Comment by slubwama** [comment]
@ssmusoke Still some errors on mysql obs https://pastebin.com/AjQeEwSR

**Comment by ssmusoke** [comment]
@slubwama you need to run the updated migration script as per this commit https://github.com/METS-Programme/openmrs-module-ugandaemr-iss/pull/1/commits/56f0e803948418c187248484866a327093125801

**Comment by slubwama** [comment]
@ssmusoke 
**ART ENCOUNTER/Followup Form** 

1. Lost color for ART Encounter Page.
2. Align ART ENCOUNTER Page Section Containing the  Type of Visit should  scale to the rest of the page.
3. Disable adherence assessment when patient is represented on ART ENCOUNTER Page.
4. Attending Clinician add in to the last  row. can not be standalone row doesn't look good where it is.
5. Duration.
6. Duration since baseline and on current regimen doesn't auto fill as requested. 
7. CTX doesn't auto calculate pill balance as requested in the document.

**-----------------------------------------------------------**
Will give more comments when discovered.

**Comment by ssmusoke** [comment]
@slubwama Noted on #1, #2 and #3. 

Please note that this is still work in progress and the Trello card will be moved when all the issues are fixed, but the aim of this PR is to be able so split up the work. Only the items in the description have been worked on todate

**Pull request merged**
