### PR TITLE
KP/PP Classification Tool

### PR DESCRIPTION
**Pull request by dbaluku**
https://trello.com/c/wvIccnHJ
Pending is Key Population and Final classifaction sections

### CODE REVIEW

**Comment by dbaluku** [comment]
1. The following concepts need to be created Other Specify for: 
- 165124 - Respondent Gender 
- 1542-Occupation

2. Change the following concepts from ConvSet to Value Coded
- 165133 - KP Classification
- 165134 - KP Final Classification

**Comment by ssmusoke** [comment]
@slubwama See concept needs

**Comment by ssmusoke** [comment]
@balukujr You can now complete this as the concepts have been updated in https://github.com/METS-Programme/openmrs-module-aijar/pull/349

**Comment by slubwama** [comment]
@balukujr resolve conflicts.

**Comment by dbaluku** [comment]
The following are pending on KP/PP classification

-  Toggling the visibility of the other specify fields on No 2 and No 4 when the "Other " option is checked in the Client Classification Section

- Correcting the concepts  for other gender and other occupation and remove the  current placeholder  concept 163174

**Comment by ssmusoke** [comment]
@balukujr merging with the remaining issues recorded at https://trello.com/c/iIA7deHT

**Comment by ssmusoke** [comment]
Merged with a followup on https://trello.com/c/iIA7deHT

**Comment by dbaluku** [comment]
Worked on auto completion of the Key Population Classification Section basing on the client information fed in.
Pending is the Young woman and adolescent girl (AGYW) field  auto completion in Key Population Classification Section.

**Pull request merged**
