### PR TITLE
Intake and Follow up Froms

### PR DESCRIPTION
**Pull request by semujju**

### CODE REVIEW

**Comment by semujju** [comment]
Screenshot from 2021-07-11 16-49-20
This page should be done as it is in uganda emr

**Comment by semujju** [comment]
The encounter part added on the health education page has some fields that are not clear, like these below
PSS Issues Identified
Depression Status
Remove the last Comment row
Put "Is Visit On Schedule" on the first row after encounter date
Add OVC Assessment
Add field for specify other PHDP Components
Add fielf for specify other linkages and referrals

**Comment by ssmusoke** [comment]
@semujju Remove the temp files which are in this directory /C:\Windows\system32\config\systemprofile\Application Data\OpenMRS\owa in your PR

**Comment by semujju** [comment]
> @semujju Remove the temp files which are in this directory /C:\Windows\system32\config\systemprofile\Application Data\OpenMRS\owa in your PR

@ssmusoke this is noted

**Pull request merged**
